############################################################################
# Contest 2026 team 137 LPTIM Stop-mode wakeup demo - Makefile
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = lptim_stop
PRIORITY  = SCHED_PRIORITY_DEFAULT
STACKSIZE = 2048
MODULE    = $(CONFIG_LVX_USE_DEMO_CONTEST2026_137_LPTIM_STOP_APP)

MAINSRC = lptim_stop_main.c

include $(APPDIR)/Application.mk
