############################################################################
# Contest 2026 team 137 AP3216C I2C4 self-test - Makefile
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = ap3216c_test
PRIORITY  = SCHED_PRIORITY_DEFAULT
STACKSIZE = 2048
MODULE    = $(CONFIG_LVX_USE_DEMO_CONTEST2026_137_AP3216C_TEST_APP)

MAINSRC = ap3216c_test_main.c

include $(APPDIR)/Application.mk
