############################################################################
# Contest 2026 team 137 HASH SHA-256 self-test - Makefile
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = hash_test
PRIORITY  = SCHED_PRIORITY_DEFAULT
STACKSIZE = 2048
MODULE    = $(CONFIG_LVX_USE_DEMO_CONTEST2026_137_HASH_TEST_APP)

MAINSRC = hash_test_main.c

include $(APPDIR)/Application.mk
