############################################################################
# Contest 2026 team 137 DMA2D RISAF-unlock experiment - Makefile
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = dma2d_unlock
PRIORITY  = SCHED_PRIORITY_DEFAULT
STACKSIZE = 2048
MODULE    = $(CONFIG_LVX_USE_DEMO_CONTEST2026_137_DMA2D_UNLOCK_APP)

MAINSRC = dma2d_unlock_main.c

include $(APPDIR)/Application.mk
