############################################################################
# Contest 2026 team 137 DMA2D de-risk probe - Makefile
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = dma2d_test
PRIORITY  = SCHED_PRIORITY_DEFAULT
STACKSIZE = 2048
MODULE    = $(CONFIG_LVX_USE_DEMO_CONTEST2026_137_DMA2D_TEST_APP)

MAINSRC = dma2d_test_main.c

include $(APPDIR)/Application.mk
