############################################################################
# Contest 2026 team 137 DTS temperature self-test - Makefile
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = dts_temp
PRIORITY  = SCHED_PRIORITY_DEFAULT
STACKSIZE = 2048
MODULE    = $(CONFIG_LVX_USE_DEMO_CONTEST2026_137_DTS_TEMP_APP)

MAINSRC = dts_temp_main.c

include $(APPDIR)/Application.mk
