############################################################################
# Contest 2026 team 137 TIM PWM+capture loopback demo - Makefile
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = tim_cap
PRIORITY  = SCHED_PRIORITY_DEFAULT
STACKSIZE = 2048
MODULE    = $(CONFIG_LVX_USE_DEMO_CONTEST2026_137_TIM_CAP_APP)

MAINSRC = tim_cap_main.c

include $(APPDIR)/Application.mk
