############################################################################
# Contest 2026 team 137 RNG entropy self-test - Makefile
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = rng_test
PRIORITY  = SCHED_PRIORITY_DEFAULT
STACKSIZE = 2048
MODULE    = $(CONFIG_LVX_USE_DEMO_CONTEST2026_137_RNG_TEST_APP)

MAINSRC = rng_test_main.c

include $(APPDIR)/Application.mk
