############################################################################
# Contest 2026 team 137 RISAF firewall write-access probe - Makefile
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = risaf_probe
PRIORITY  = SCHED_PRIORITY_DEFAULT
STACKSIZE = 2048
MODULE    = $(CONFIG_LVX_USE_DEMO_CONTEST2026_137_RISAF_PROBE_APP)

MAINSRC = risaf_probe_main.c

include $(APPDIR)/Application.mk
